# Generated by Django 6.1.1 on 2026-09-06 08:55

import common.db
import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
import django.db.models.functions.comparison
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('organization', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('holiday_date', models.DateField()),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_paid', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled')], default='active', max_length=16)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='holidays', to='organization.branch')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_holidays', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'scheduling_holiday',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('spans_next_day', models.BooleanField(default=False)),
                ('scheduled_minutes', models.PositiveIntegerField()),
                ('grace_in_minutes', models.PositiveIntegerField(default=0)),
                ('grace_out_minutes', models.PositiveIntegerField(default=0)),
                ('minimum_full_day_minutes', models.PositiveIntegerField(default=0)),
                ('minimum_half_day_minutes', models.PositiveIntegerField(default=0)),
                ('default_break_minutes', models.PositiveIntegerField(default=0)),
                ('break_is_paid', models.BooleanField(default=False)),
                ('overtime_after_minutes', models.PositiveIntegerField(default=0)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=16)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'scheduling_shift',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeShiftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('effective_from', models.DateTimeField()),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('assignment_type', models.CharField(choices=[('department_selection', 'Department selection'), ('employee_override', 'Employee override'), ('temporary', 'Temporary')], default='department_selection', max_length=32)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('ended', 'Ended'), ('cancelled', 'Cancelled')], default='active', max_length=16)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shift_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shift_assignments', to='employees.employee')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_assignments', to='scheduling.shift')),
            ],
            options={
                'db_table': 'scheduling_employeeshiftassignment',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_default', models.BooleanField(default=False)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('ended', 'Ended')], default='active', max_length=16)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shift_links', to='organization.department')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='department_links', to='scheduling.shift')),
            ],
            options={
                'db_table': 'scheduling_departmentshift',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='CompanyAttendanceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shift_mode', models.CharField(choices=[('company_single_shift', 'One shift for the company'), ('department_shifts', 'Shifts per department')], default='company_single_shift', max_length=32)),
                ('punch_pairing_strategy', models.CharField(default='alternating', max_length=32)),
                ('device_attendance_scope', models.CharField(choices=[('assigned_devices', 'Assigned devices only'), ('department_devices', 'Department devices'), ('branch_devices', 'Branch devices'), ('company_devices', 'Company devices')], default='assigned_devices', max_length=32)),
                ('duplicate_punch_window_seconds', models.PositiveIntegerField(default=30)),
                ('attendance_window_before_minutes', models.PositiveIntegerField(default=120)),
                ('attendance_window_after_minutes', models.PositiveIntegerField(default=120)),
                ('missing_punch_policy', models.CharField(choices=[('review_required', 'Review required'), ('auto_absent', 'Treat as absent')], default='review_required', max_length=32)),
                ('overtime_requires_approval', models.BooleanField(default=True)),
                ('round_work_minutes_to', models.PositiveIntegerField(default=1)),
                ('round_overtime_minutes_to', models.PositiveIntegerField(default=1)),
                ('settings_version', models.PositiveIntegerField(default=1)),
                ('effective_from', models.DateTimeField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('company_shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='companies_using_as_single_shift', to='scheduling.shift')),
            ],
            options={
                'verbose_name_plural': 'company attendance settings',
                'db_table': 'scheduling_companyattendancesettings',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyOffRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('is_paid', models.BooleanField(default=True)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('ended', 'Ended')], default='active', max_length=16)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='weekly_off_rules', to='organization.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'scheduling_weeklyoffrule',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='HolidayWorkAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work_date', models.DateField()),
                ('treatment', models.CharField(choices=[('normal_workday', 'Normal workday'), ('overtime', 'Overtime'), ('compensatory_leave', 'Compensatory leave'), ('overtime_and_comp_leave', 'Overtime + comp leave')], default='normal_workday', max_length=32)),
                ('reason', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('cancelled', 'Cancelled')], default='draft', max_length=16)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_holiday_work', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holiday_work', to='employees.employee')),
                ('holiday', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_assignments', to='scheduling.holiday')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='holiday_work_assignments', to='scheduling.shift')),
                ('weekly_off_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_assignments', to='scheduling.weeklyoffrule')),
            ],
            options={
                'db_table': 'scheduling_holidayworkassignment',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='holiday',
            index=models.Index(fields=['company', 'holiday_date'], name='scheduling__company_21ed45_idx'),
        ),
        migrations.AddConstraint(
            model_name='holiday',
            constraint=models.UniqueConstraint(models.F('company'), models.F('holiday_date'), django.db.models.functions.comparison.Coalesce('branch', 0, output_field=models.BigIntegerField()), condition=models.Q(('status', 'active')), name='uniq_active_holiday_per_scope_date'),
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uniq_shift_code_per_company'),
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.CheckConstraint(condition=models.Q(('scheduled_minutes__gt', 0)), name='shift_scheduled_minutes_positive'),
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_half_day_minutes__lte', models.F('minimum_full_day_minutes'))), name='shift_half_day_not_over_full_day'),
        ),
        migrations.AddIndex(
            model_name='employeeshiftassignment',
            index=models.Index(fields=['company', 'employee', 'effective_from'], name='scheduling__company_81aa76_idx'),
        ),
        migrations.AddConstraint(
            model_name='employeeshiftassignment',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gt', models.F('effective_from')), _connector='OR'), name='shiftassignment_period_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='employeeshiftassignment',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status', 'cancelled'), _negated=True), expressions=[('company', '='), ('employee', '='), (common.db.TstzRange('effective_from', 'effective_to', django.contrib.postgres.fields.ranges.RangeBoundary()), '&&')], name='excl_employee_shift_overlap'),
        ),
        migrations.AddConstraint(
            model_name='departmentshift',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gt', models.F('effective_from')), _connector='OR'), name='departmentshift_period_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='departmentshift',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(expressions=[('company', '='), ('department', '='), ('shift', '='), (common.db.DateRange('effective_from', 'effective_to', django.contrib.postgres.fields.ranges.RangeBoundary()), '&&')], name='excl_departmentshift_duplicate_period'),
        ),
        migrations.AddConstraint(
            model_name='departmentshift',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('is_default', True)), expressions=[('company', '='), ('department', '='), (common.db.DateRange('effective_from', 'effective_to', django.contrib.postgres.fields.ranges.RangeBoundary()), '&&')], name='excl_departmentshift_single_default'),
        ),
        migrations.AddConstraint(
            model_name='companyattendancesettings',
            constraint=models.UniqueConstraint(fields=('company',), name='uniq_attendance_settings_per_company'),
        ),
        migrations.AddConstraint(
            model_name='companyattendancesettings',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('shift_mode', 'company_single_shift'), _negated=True), ('company_shift__isnull', False), _connector='OR'), name='single_shift_mode_requires_company_shift'),
        ),
        migrations.AddConstraint(
            model_name='weeklyoffrule',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gt', models.F('effective_from')), _connector='OR'), name='weeklyoff_period_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='weeklyoffrule',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(expressions=[('company', '='), (django.db.models.functions.comparison.Coalesce('branch', 0, output_field=models.BigIntegerField()), '='), ('weekday', '='), (common.db.DateRange('effective_from', 'effective_to', django.contrib.postgres.fields.ranges.RangeBoundary()), '&&')], name='excl_weeklyoff_duplicate_period'),
        ),
        migrations.AddIndex(
            model_name='holidayworkassignment',
            index=models.Index(fields=['company', 'work_date'], name='scheduling__company_226d69_idx'),
        ),
        migrations.AddConstraint(
            model_name='holidayworkassignment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('holiday__isnull', False), ('weekly_off_rule__isnull', True)), models.Q(('holiday__isnull', True), ('weekly_off_rule__isnull', False)), _connector='OR'), name='holidaywork_exactly_one_source'),
        ),
        migrations.AddConstraint(
            model_name='holidayworkassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'cancelled'), _negated=True), fields=('company', 'employee', 'work_date'), name='uniq_live_holiday_work_per_employee_date'),
        ),
    ]
