# Generated by Django 6.1.1 on 2026-09-19 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_remove_companydepartment_organizatio_company_31e7ff_idx_and_more'),
        ('scheduling', '0002_departmentshift_company_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentshift',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shift_links', to='organization.department'),
        ),
    ]
