# Generated by Django 6.1.1 on 2026-10-03 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_repeat_scan_window_5_seconds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyattendancesettings',
            name='punch_pairing_strategy',
            field=models.CharField(choices=[('alternating', 'Scans alternate in and out - breaks are measured'), ('first_last', 'First scan is the check-in, last scan the check-out')], default='alternating', max_length=32),
        ),
    ]
