# Generated by Django 6.1.1 on 2026-10-07 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0005_pairing_strategy_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyattendancesettings',
            name='came_in_is_half_day',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='companyattendancesettings',
            name='late_made_up_after_shift',
            field=models.BooleanField(default=True),
        ),
    ]
