# Generated by Django 6.1.1 on 2026-10-01 05:09

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0007_inactive_periods'),
        ('tenants', '0006_company_contact_person'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookDayState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work_date', models.DateField()),
                ('check_in', models.DateTimeField(blank=True, null=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='employees.employee')),
            ],
            options={
                'db_table': 'webhooks_day_state',
                'constraints': [models.UniqueConstraint(fields=('employee', 'work_date'), name='uniq_webhook_day_state')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('work_date', models.DateField()),
                ('kind', models.CharField(choices=[('check_in', 'Check-in'), ('check_out', 'Check-out'), ('update', 'Changed')], max_length=16)),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Waiting to be sent'), ('sent', 'Received'), ('failed', 'Not received - will try again'), ('skipped', 'Refused by the receiver'), ('gave_up', 'Given up')], default='pending', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField()),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('last_message', models.CharField(blank=True, max_length=500)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='webhook_events', to='employees.employee')),
            ],
            options={
                'db_table': 'webhooks_event',
                'indexes': [models.Index(fields=['company', 'status', 'next_attempt_at'], name='webhooks_ev_company_3b87f6_idx'), models.Index(fields=['company', 'employee', 'work_date'], name='webhooks_ev_company_b0ffa6_idx')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='WebhookSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('url', models.URLField(max_length=500)),
                ('ping_url', models.URLField(blank=True, max_length=500)),
                ('auth', models.CharField(choices=[('header', 'X-Webhook-Secret header'), ('bearer', 'Authorization: Bearer header')], default='header', max_length=16)),
                ('secret_encrypted', models.TextField(blank=True)),
                ('signing_secret_encrypted', models.TextField(blank=True)),
                ('employee_key', models.CharField(default='au_user_id', max_length=40)),
                ('mode', models.CharField(choices=[('arrive_leave', 'When they come in, and when their day is finished'), ('every_scan', 'After every scan (first in and latest out so far)')], default='arrive_leave', max_length=16)),
                ('batch', models.BooleanField(default=True)),
                ('send_from', models.DateField(blank=True, null=True)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_ok', models.BooleanField(blank=True, null=True)),
                ('last_test_message', models.CharField(blank=True, max_length=500)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'webhook settings',
                'db_table': 'webhooks_settings',
                'constraints': [models.UniqueConstraint(fields=('company',), name='uniq_webhook_settings_per_company')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
