# Generated by Django 6.1.1 on 2026-10-01 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhookevent',
            name='kind',
            field=models.CharField(choices=[('check_in', 'Check-in'), ('check_out', 'Check-out'), ('update', 'Changed'), ('test', 'Test (sent by hand)')], max_length=16),
        ),
    ]
