# Generated by Django 6.1.1 on 2026-10-03 04:37

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_company_contact_person'),
        ('webhooks', '0002_test_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhooksettings',
            name='debug_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='WebhookDebugEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('what', models.CharField(max_length=32)),
                ('ok', models.BooleanField(null=True)),
                ('message', models.TextField()),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.company')),
            ],
            options={
                'db_table': 'webhooks_debug_entry',
                'indexes': [models.Index(fields=['company', 'created_at'], name='webhooks_de_company_6f9ce7_idx')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
