# Generated by Django 6.1.1 on 2026-10-03 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0003_debug_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhooksettings',
            name='polled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
