# Generated by Django 6.1.1 on 2026-10-03 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0004_poll_once_a_minute'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookdaystate',
            name='breaks_sent',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='webhooksettings',
            name='send_breaks',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='webhookevent',
            name='kind',
            field=models.CharField(choices=[('check_in', 'Check-in'), ('check_out', 'Check-out'), ('update', 'Changed'), ('test', 'Test (sent by hand)'), ('break_out', 'Out for a break'), ('break_in', 'Back from a break')], max_length=16),
        ),
    ]
