# Generated by Django 6.1.1 on 2026-09-19 07:25

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employeeassignment_department_and_more'),
        ('organization', '0004_designation_independent_of_department'),
        ('tenants', '0006_company_contact_person'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='companydepartment',
            name='organizatio_company_31e7ff_idx',
        ),
        migrations.RemoveConstraint(
            model_name='companydepartment',
            name='uniq_companydepartment_per_branch',
        ),
        migrations.RemoveIndex(
            model_name='companydesignation',
            name='organizatio_company_eb7205_idx',
        ),
        migrations.RemoveConstraint(
            model_name='companydesignation',
            name='uniq_companydesignation_per_department',
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ('branch__name', 'name')},
        ),
        migrations.AlterModelOptions(
            name='designation',
            options={'ordering': ('department__name', 'name')},
        ),
        migrations.AlterModelManagers(
            name='department',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='designation',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='departments', to='organization.branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='closed_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='headed_departments', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='department',
            name='opened_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='designation',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='designation',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='designations', to='organization.department'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='designation',
            name='hierarchy_level',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='designation',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='organization.designation'),
        ),
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='designation',
            name='code',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='designation',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['company', 'branch'], name='organizatio_company_f3cc50_idx'),
        ),
        migrations.AddIndex(
            model_name='designation',
            index=models.Index(fields=['company', 'department'], name='organizatio_company_c6f32e_idx'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('branch', 'code'), name='uniq_department_code_per_branch'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('branch', 'name'), name='uniq_department_name_per_branch'),
        ),
        migrations.AddConstraint(
            model_name='designation',
            constraint=models.UniqueConstraint(fields=('department', 'code'), name='uniq_designation_code_per_department'),
        ),
        migrations.AddConstraint(
            model_name='designation',
            constraint=models.CheckConstraint(condition=models.Q(('parent', models.F('id')), _negated=True), name='designation_parent_not_self'),
        ),
        migrations.RemoveField(
            model_name='companydepartment',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='companydepartment',
            name='company',
        ),
        migrations.RemoveField(
            model_name='companydepartment',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='companydepartment',
            name='department',
        ),
        migrations.RemoveField(
            model_name='companydepartment',
            name='head',
        ),
        migrations.RemoveField(
            model_name='companydepartment',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='companydesignation',
            name='company',
        ),
        migrations.RemoveField(
            model_name='companydesignation',
            name='company_department',
        ),
        migrations.RemoveField(
            model_name='companydesignation',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='companydesignation',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='companydesignation',
            name='updated_by',
        ),
    ]
