# Generated by Django 6.1.1 on 2026-09-19 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0003_alter_departmentpermission_company_department_and_more'),
        ('accounts', '0006_remove_companymembership_allowed_departments_and_more'),
        ('devices', '0005_alter_devicedepartment_department'),
        ('employees', '0003_alter_employeeassignment_department_and_more'),
        ('organization', '0005_remove_companydepartment_organizatio_company_31e7ff_idx_and_more'),
        ('scheduling', '0003_alter_departmentshift_department'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyDepartment',
        ),
        migrations.DeleteModel(
            name='CompanyDesignation',
        ),
    ]
