# Generated by Django 6.1.1 on 2026-09-08 10:15

import common.db
import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        # DeviceDepartment points at the company adoption row, which arrives in
        # organization.0002. Depending on 0001 would let this migration render
        # against a state where CompanyDepartment does not exist yet.
        ('organization', '0002_company_department_designation'),
        ('tenants', '0004_company_code_sequence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=150)),
                ('protocol', models.CharField(choices=[('adms_push', 'ADMS push'), ('webhook', 'Webhook'), ('vendor_cloud_api', 'Vendor cloud API'), ('file_import', 'File import'), ('other', 'Other')], max_length=32)),
                ('capabilities', models.JSONField(blank=True, default=dict)),
                ('supported_template_formats', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'devices_devicemodel',
            },
        ),
        migrations.CreateModel(
            name='DeviceVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('adapter_key', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
                ('support_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'devices_devicevendor',
            },
        ),
        migrations.CreateModel(
            name='BiometricDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('serial_number', models.CharField(max_length=100)),
                ('external_device_id', models.CharField(blank=True, max_length=100)),
                ('timezone', models.CharField(max_length=64)),
                ('authentication_key_id', models.CharField(blank=True, max_length=100)),
                ('authentication_secret_hash', models.CharField(blank=True, max_length=255)),
                ('firmware_version', models.CharField(blank=True, max_length=64)),
                ('ip_address_last_seen', models.GenericIPAddressField(blank=True, null=True)),
                ('installed_at', models.DateTimeField(blank=True, null=True)),
                ('decommissioned_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('clock_offset_seconds', models.IntegerField(blank=True, null=True)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('offline', 'Offline'), ('suspended', 'Suspended'), ('retired', 'Retired')], default='pending', max_length=16)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='biometric_devices', to='organization.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('device_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='devices.devicemodel')),
            ],
            options={
                'db_table': 'devices_biometricdevice',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='BiometricTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('biometric_type', models.CharField(choices=[('fingerprint', 'Fingerprint'), ('face', 'Face')], max_length=16)),
                ('finger_position', models.CharField(blank=True, choices=[('left_thumb', 'Left thumb'), ('left_index', 'Left index'), ('left_middle', 'Left middle'), ('left_ring', 'Left ring'), ('left_little', 'Left little'), ('right_thumb', 'Right thumb'), ('right_index', 'Right index'), ('right_middle', 'Right middle'), ('right_ring', 'Right ring'), ('right_little', 'Right little')], max_length=16)),
                ('template_format', models.CharField(max_length=32)),
                ('template_version', models.CharField(max_length=32)),
                ('encrypted_template_data', models.BinaryField()),
                ('encryption_key_version', models.CharField(max_length=32)),
                ('template_checksum', models.CharField(max_length=128)),
                ('template_size_bytes', models.PositiveIntegerField(blank=True, null=True)),
                ('quality_score', models.PositiveIntegerField(blank=True, null=True)),
                ('captured_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked'), ('incompatible', 'Incompatible'), ('deleted_pending', 'Deletion pending')], default='active', max_length=16)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.TextField(blank=True)),
                ('captured_from_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captured_templates', to='devices.biometricdevice')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='biometric_templates', to='employees.employee')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('compatible_device_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compatible_templates', to='devices.devicemodel')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='biometric_templates', to='devices.devicevendor')),
            ],
            options={
                'db_table': 'devices_biometrictemplate',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DeviceEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_user_id', models.CharField(max_length=100)),
                ('card_number', models.CharField(blank=True, max_length=255)),
                ('device_privilege', models.CharField(choices=[('normal_user', 'Normal user'), ('device_admin', 'Device admin'), ('other', 'Other')], default='normal_user', max_length=16)),
                ('attendance_enabled', models.BooleanField(default=True)),
                ('assigned_device_authorized', models.BooleanField(default=False)),
                ('effective_from', models.DateTimeField()),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('enrollment_status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('synced', 'Synced'), ('failed', 'Failed'), ('removed', 'Removed')], default='pending', max_length=16)),
                ('vendor_enrollment_revision', models.CharField(blank=True, max_length=100)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('sync_error_code', models.CharField(blank=True, max_length=64)),
                ('sync_error_message', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='devices.biometricdevice')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='device_enrollments', to='employees.employee')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'devices_deviceenrollment',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DeviceEnrollmentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_template_id', models.CharField(blank=True, max_length=100)),
                ('deployment_status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('synced', 'Synced'), ('failed', 'Failed'), ('removed', 'Removed')], default='pending', max_length=16)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('deployed_at', models.DateTimeField(blank=True, null=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_code', models.CharField(blank=True, max_length=64)),
                ('last_error_message', models.TextField(blank=True)),
                ('source_key', models.CharField(max_length=150)),
                ('biometric_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='device_deployments', to='devices.biometrictemplate')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.company')),
                ('device_enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='template_deployments', to='devices.deviceenrollment')),
            ],
            options={
                'db_table': 'devices_deviceenrollmenttemplate',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DeviceMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('message_type', models.CharField(choices=[('punch_batch', 'Punch batch'), ('heartbeat', 'Heartbeat'), ('enrollment_result', 'Enrollment result'), ('command_result', 'Command result'), ('device_info', 'Device info'), ('unknown', 'Unknown')], max_length=32)),
                ('vendor_message_id', models.CharField(blank=True, max_length=150)),
                ('vendor_sequence', models.CharField(blank=True, max_length=100)),
                ('idempotency_key', models.CharField(blank=True, max_length=200)),
                ('occurred_at_device', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(db_index=True)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('encoding', models.CharField(blank=True, max_length=32)),
                ('raw_payload_text', models.TextField(blank=True, null=True)),
                ('raw_payload_binary', models.BinaryField(blank=True, null=True)),
                ('payload_json', models.JSONField(blank=True, null=True)),
                ('payload_hash', models.CharField(max_length=128)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('request_headers_snapshot', models.JSONField(blank=True, null=True)),
                ('record_count', models.PositiveIntegerField(blank=True, null=True)),
                ('processing_status', models.CharField(choices=[('received', 'Received'), ('parsing', 'Parsing'), ('parsed', 'Parsed'), ('partially_failed', 'Partially failed'), ('failed', 'Failed')], default='received', max_length=20)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_attempts', models.PositiveIntegerField(default=0)),
                ('processing_error', models.TextField(blank=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='device_messages', to='organization.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.company')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='devices.biometricdevice')),
            ],
            options={
                'db_table': 'devices_devicemessage',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DeviceSyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_vendor_sequence', models.CharField(blank=True, max_length=100)),
                ('last_vendor_cursor', models.CharField(blank=True, max_length=255)),
                ('last_device_event_at', models.DateTimeField(blank=True, null=True)),
                ('last_message_received_at', models.DateTimeField(blank=True, null=True)),
                ('last_punch_received_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_code', models.CharField(blank=True, max_length=64)),
                ('last_error_message', models.TextField(blank=True)),
                ('consecutive_error_count', models.PositiveIntegerField(default=0)),
                ('estimated_backlog_count', models.PositiveIntegerField(default=0)),
                ('clock_offset_seconds', models.IntegerField(blank=True, null=True)),
                ('state_data', models.JSONField(blank=True, default=dict)),
                ('version', models.PositiveBigIntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.company')),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sync_state', to='devices.biometricdevice')),
            ],
            options={
                'db_table': 'devices_devicesyncstate',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='models', to='devices.devicevendor'),
        ),
        migrations.CreateModel(
            name='PunchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_user_id', models.CharField(max_length=100)),
                ('vendor_punch_id', models.CharField(blank=True, max_length=150)),
                ('vendor_sequence', models.CharField(blank=True, max_length=100)),
                ('source_record_index', models.PositiveIntegerField()),
                ('punched_at_device_raw', models.CharField(max_length=100)),
                ('punched_at_device', models.DateTimeField()),
                ('punched_at_utc', models.DateTimeField()),
                ('device_timezone', models.CharField(blank=True, max_length=64)),
                ('utc_offset_minutes', models.IntegerField(blank=True, null=True)),
                ('received_at', models.DateTimeField()),
                ('verification_method', models.CharField(choices=[('fingerprint', 'Fingerprint'), ('face', 'Face'), ('card', 'Card'), ('pin', 'PIN'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('reported_direction', models.CharField(blank=True, max_length=16)),
                ('reported_status_code', models.CharField(blank=True, max_length=32)),
                ('raw_record', models.JSONField()),
                ('authorization_status', models.CharField(choices=[('authorized', 'Authorized'), ('unauthorized_device', 'Unauthorized device'), ('unknown_employee', 'Unknown employee'), ('expired_enrollment', 'Expired enrollment'), ('department_mismatch', 'Department mismatch'), ('branch_mismatch', 'Branch mismatch'), ('enrollment_disabled', 'Enrollment disabled'), ('policy_unresolved', 'Policy unresolved')], default='policy_unresolved', max_length=32)),
                ('authorization_snapshot', models.JSONField(blank=True, default=dict)),
                ('dedupe_status', models.CharField(choices=[('unique', 'Unique'), ('probable_duplicate', 'Probable duplicate'), ('confirmed_duplicate', 'Confirmed duplicate')], default='unique', max_length=20)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('allocated', 'Allocated'), ('excluded', 'Excluded'), ('needs_review', 'Needs review'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('processing_error', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='punch_events', to='organization.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.company')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='punch_events', to='devices.biometricdevice')),
                ('device_enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='punch_events', to='devices.deviceenrollment')),
                ('device_message', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='punch_events', to='devices.devicemessage')),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='duplicates', to='devices.punchevent')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='punch_events', to='employees.employee')),
            ],
            options={
                'db_table': 'devices_punchevent',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DeviceDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('effective_from', models.DateTimeField()),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('ended', 'Ended')], default='active', max_length=16)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='device_links', to='organization.companydepartment')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='department_links', to='devices.biometricdevice')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'devices_devicedepartment',
                'indexes': [models.Index(fields=['company', 'device', 'effective_from'], name='devices_dev_company_a04e31_idx'), models.Index(fields=['company', 'department'], name='devices_dev_company_dcb44f_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gt', models.F('effective_from')), _connector='OR'), name='devicedepartment_period_end_after_start'), django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status', 'ended'), _negated=True), expressions=[('company', '='), ('device', '='), ('department', '='), (common.db.TstzRange('effective_from', 'effective_to', django.contrib.postgres.fields.ranges.RangeBoundary()), '&&')], name='excl_devicedepartment_overlap')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='deviceenrollment',
            index=models.Index(fields=['company', 'device', 'device_user_id'], name='devices_dev_company_ff6127_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceenrollment',
            index=models.Index(fields=['company', 'employee'], name='devices_dev_company_b8981f_idx'),
        ),
        migrations.AddConstraint(
            model_name='deviceenrollment',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gt', models.F('effective_from')), _connector='OR'), name='deviceenrollment_period_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='deviceenrollment',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('enrollment_status', 'removed'), _negated=True), expressions=[('company', '='), ('device', '='), ('device_user_id', '='), (common.db.TstzRange('effective_from', 'effective_to', django.contrib.postgres.fields.ranges.RangeBoundary()), '&&')], name='excl_deviceenrollment_user_id_overlap'),
        ),
        migrations.AddConstraint(
            model_name='deviceenrollment',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('enrollment_status', 'removed'), _negated=True), expressions=[('company', '='), ('device', '='), ('employee', '='), (common.db.TstzRange('effective_from', 'effective_to', django.contrib.postgres.fields.ranges.RangeBoundary()), '&&')], name='excl_deviceenrollment_employee_device_overlap'),
        ),
        migrations.AddIndex(
            model_name='deviceenrollmenttemplate',
            index=models.Index(fields=['company', 'device_enrollment'], name='devices_dev_company_bf9779_idx'),
        ),
        migrations.AddConstraint(
            model_name='deviceenrollmenttemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('deployment_status', 'removed'), _negated=True), fields=('device_enrollment', 'biometric_template'), name='uniq_deviceenrollmenttemplate_active'),
        ),
        migrations.AddIndex(
            model_name='devicemessage',
            index=models.Index(fields=['company', 'device', 'received_at'], name='devices_dev_company_a158e9_idx'),
        ),
        migrations.AddIndex(
            model_name='devicemessage',
            index=models.Index(fields=['company', 'processing_status'], name='devices_dev_company_9203bc_idx'),
        ),
        migrations.AddConstraint(
            model_name='devicemessage',
            constraint=models.CheckConstraint(condition=models.Q(('raw_payload_text__isnull', False), ('raw_payload_binary__isnull', False), _connector='OR'), name='devicemessage_has_raw_representation'),
        ),
        migrations.AddConstraint(
            model_name='devicemessage',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('device', 'idempotency_key'), name='uniq_devicemessage_device_idempotency_key'),
        ),
        migrations.AddIndex(
            model_name='biometricdevice',
            index=models.Index(fields=['company', 'status'], name='devices_bio_company_88b3b2_idx'),
        ),
        migrations.AddIndex(
            model_name='biometricdevice',
            index=models.Index(fields=['company', 'branch'], name='devices_bio_company_d7cdc6_idx'),
        ),
        migrations.AddConstraint(
            model_name='biometricdevice',
            constraint=models.UniqueConstraint(fields=('company', 'serial_number'), name='uniq_biometricdevice_company_serial'),
        ),
        migrations.AddConstraint(
            model_name='devicemodel',
            constraint=models.UniqueConstraint(fields=('vendor', 'model_code'), name='uniq_devicemodel_vendor_code'),
        ),
        migrations.AddIndex(
            model_name='biometrictemplate',
            index=models.Index(fields=['company', 'employee', 'biometric_type'], name='devices_bio_company_9116a9_idx'),
        ),
        migrations.AddConstraint(
            model_name='biometrictemplate',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('biometric_type', 'face'), _negated=True), ('finger_position', ''), _connector='OR'), name='biometrictemplate_face_has_no_finger_position'),
        ),
        migrations.AddConstraint(
            model_name='biometrictemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('company', 'employee', 'biometric_type', 'template_format', 'template_checksum'), name='uniq_biometrictemplate_active_checksum'),
        ),
        migrations.AddIndex(
            model_name='punchevent',
            index=models.Index(fields=['company', 'device', 'punched_at_utc'], name='devices_pun_company_cd5ddd_idx'),
        ),
        migrations.AddIndex(
            model_name='punchevent',
            index=models.Index(fields=['company', 'employee', 'punched_at_utc'], name='devices_pun_company_a4ddd5_idx'),
        ),
        migrations.AddIndex(
            model_name='punchevent',
            index=models.Index(fields=['company', 'authorization_status'], name='devices_pun_company_5f9247_idx'),
        ),
        migrations.AddIndex(
            model_name='punchevent',
            index=models.Index(fields=['company', 'dedupe_status'], name='devices_pun_company_5d17b3_idx'),
        ),
        migrations.AddIndex(
            model_name='punchevent',
            index=models.Index(fields=['company', 'processing_status'], name='devices_pun_company_52b54e_idx'),
        ),
        migrations.AddConstraint(
            model_name='punchevent',
            constraint=models.UniqueConstraint(fields=('device_message', 'source_record_index'), name='uniq_punchevent_message_record_index'),
        ),
        migrations.AddConstraint(
            model_name='punchevent',
            constraint=models.UniqueConstraint(condition=models.Q(('vendor_punch_id', ''), _negated=True), fields=('device', 'vendor_punch_id'), name='uniq_punchevent_device_vendor_punch_id'),
        ),
    ]
