# Generated by Django 6.0.7 on 2026-09-12 09:48

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_seed_hardware_catalogue'),
        ('tenants', '0005_alter_feature_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='biometricdevice',
            name='server_host',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='biometricdevice',
            name='server_port',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biometricdevice',
            name='server_scheme',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.CreateModel(
            name='DeviceServerAddressChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('previous_scheme', models.CharField(blank=True, max_length=8)),
                ('previous_host', models.CharField(blank=True, max_length=255)),
                ('previous_port', models.PositiveIntegerField(blank=True, null=True)),
                ('new_scheme', models.CharField(max_length=8)),
                ('new_host', models.CharField(max_length=255)),
                ('new_port', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('checking', 'Checking the new address'), ('unreachable', 'Address not reachable'), ('queued', 'Waiting for the device to pick up the change'), ('delivered', 'Device received the change'), ('acknowledged', 'Device acknowledged the change'), ('confirmed', 'Connected at the new address'), ('not_applied', 'Device did not apply the change'), ('lost', 'Device not reachable at the new address'), ('cancelled', 'Cancelled')], default='checking', max_length=16)),
                ('probe_token', models.CharField(blank=True, max_length=64)),
                ('probe_started_at', models.DateTimeField(blank=True, null=True)),
                ('probe_completed_at', models.DateTimeField(blank=True, null=True)),
                ('command_id', models.IntegerField(blank=True, null=True)),
                ('port_command_id', models.IntegerField(blank=True, null=True)),
                ('command_queued_at', models.DateTimeField(blank=True, null=True)),
                ('command_delivered_at', models.DateTimeField(blank=True, null=True)),
                ('command_acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('command_return_code', models.CharField(blank=True, max_length=32)),
                ('seen_at_new_address_at', models.DateTimeField(blank=True, null=True)),
                ('seen_at_old_address_at', models.DateTimeField(blank=True, null=True)),
                ('deadline_at', models.DateTimeField(blank=True, null=True)),
                ('failure_code', models.CharField(blank=True, max_length=32)),
                ('failure_reason', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='address_changes', to='devices.biometricdevice')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'devices_deviceserveraddresschange',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['company', 'device', '-created_at'], name='devices_dev_company_47c3c9_idx'), models.Index(fields=['company', 'status'], name='devices_dev_company_8b7040_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ('checking', 'queued', 'delivered', 'acknowledged'))), fields=('device',), name='uniq_device_address_change_in_flight')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
