# Generated by Django 6.1.1 on 2026-09-19 07:30

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_seed_senseface_3a'),
        ('tenants', '0006_company_contact_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceUserTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_user_id', models.CharField(max_length=64)),
                ('bio_type', models.CharField(choices=[('fingerprint', 'Fingerprint'), ('face', 'Face'), ('other', 'Other')], max_length=16)),
                ('vendor_type', models.CharField(max_length=8)),
                ('number', models.CharField(blank=True, max_length=8)),
                ('index', models.CharField(blank=True, max_length=8)),
                ('valid', models.CharField(blank=True, max_length=4)),
                ('duress', models.CharField(blank=True, max_length=4)),
                ('major_version', models.CharField(blank=True, max_length=16)),
                ('minor_version', models.CharField(blank=True, max_length=16)),
                ('template_format', models.CharField(blank=True, max_length=16)),
                ('template_encrypted', models.BinaryField()),
                ('template_sha256', models.CharField(max_length=64)),
                ('template_length', models.PositiveIntegerField()),
                ('captured_at', models.DateTimeField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.company')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_templates', to='devices.biometricdevice')),
                ('device_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='devices.devicemodel')),
            ],
            options={
                'db_table': 'devices_device_user_template',
                'indexes': [models.Index(fields=['company', 'device', 'device_user_id'], name='devices_dev_company_018175_idx')],
                'constraints': [models.UniqueConstraint(fields=('device', 'device_user_id', 'vendor_type', 'number', 'index'), name='uniq_device_user_template')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
