# Generated by Django 6.1.1 on 2026-09-19 10:49

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_device_user_template'),
        ('tenants', '0006_company_contact_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceOutboxCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('command_id', models.PositiveIntegerField()),
                ('key', models.CharField(max_length=120)),
                ('device_user_id', models.CharField(blank=True, max_length=64)),
                ('description', models.TextField()),
                ('body', models.TextField(blank=True)),
                ('body_encrypted', models.BinaryField(blank=True, null=True)),
                ('status', models.CharField(choices=[('queued', 'Waiting for the device'), ('sent', 'Sent'), ('done', 'Done'), ('refused', 'Refused by the device'), ('dropped', 'Not sent')], default='queued', max_length=16)),
                ('return_code', models.CharField(blank=True, max_length=64)),
                ('requested_by', models.CharField(blank=True, max_length=254)),
                ('queued_at', models.DateTimeField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.company')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbox', to='devices.biometricdevice')),
            ],
            options={
                'db_table': 'devices_device_outbox_command',
                'indexes': [models.Index(fields=['device', 'status', 'command_id'], name='devices_dev_device__3c58d0_idx')],
                'constraints': [models.UniqueConstraint(fields=('device', 'command_id'), name='uniq_outbox_device_command')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
