# Generated by Django 6.1.1 on 2026-09-29 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_first_placements_start_at_midnight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punchevent',
            name='authorization_status',
            field=models.CharField(choices=[('authorized', 'Authorized'), ('unauthorized_device', 'Unauthorized device'), ('unknown_employee', 'Unknown employee'), ('expired_enrollment', 'Expired enrollment'), ('department_mismatch', 'Department mismatch'), ('branch_mismatch', 'Branch mismatch'), ('enrollment_disabled', 'Enrollment disabled'), ('policy_unresolved', 'Policy unresolved'), ('employee_inactive', 'Blocked: employee inactive')], default='policy_unresolved', max_length=32),
        ),
    ]
