# Generated by Django 6.1.1 on 2026-09-06 06:29

import common.db
import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.contrib.postgres.operations import BtreeGistExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Exclusion constraints combine equality (=) on scalar columns with
        # range overlap (&&) in one GiST index; btree_gist supplies the
        # equality operator classes GiST needs for those scalar columns.
        BtreeGistExtension(),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('middle_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('preferred_name', models.CharField(blank=True, max_length=150)),
                ('work_email', models.EmailField(blank=True, max_length=254)),
                ('personal_email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=32)),
                ('blood_group', models.CharField(blank=True, max_length=8)),
                ('marital_status', models.CharField(blank=True, max_length=32)),
                ('national_id', models.CharField(blank=True, max_length=64)),
                ('passport_number', models.CharField(blank=True, max_length=64)),
                ('address', models.TextField(blank=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=150)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=32)),
                ('emergency_contact_relation', models.CharField(blank=True, max_length=64)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('confirmation_date', models.DateField(blank=True, null=True)),
                ('leaving_date', models.DateField(blank=True, null=True)),
                ('employment_status', models.CharField(choices=[('applicant', 'Applicant'), ('active', 'Active'), ('probation', 'Probation'), ('suspended', 'Suspended'), ('resigned', 'Resigned'), ('terminated', 'Terminated'), ('retired', 'Retired')], default='active', max_length=16)),
                ('photo', models.FileField(blank=True, null=True, upload_to='employee_photos/')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'employees_employee',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_code', models.CharField(max_length=64)),
                ('effective_from', models.DateTimeField()),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('change_reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('ended', 'Ended'), ('cancelled', 'Cancelled')], default='active', max_length=16)),
                ('device_attendance_scope_override', models.CharField(blank=True, choices=[('assigned_devices', 'Assigned devices only'), ('department_devices', 'Department devices'), ('branch_devices', 'Branch devices'), ('company_devices', 'Company devices')], max_length=32, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='organization.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='organization.department')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='organization.designation')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='employees.employee')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='direct_reports', to='employees.employee')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'employees_employeeassignment',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeCompensation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pay_basis', models.CharField(choices=[('monthly', 'Monthly'), ('daily', 'Daily'), ('hourly', 'Hourly')], max_length=16)),
                ('base_rate', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(max_length=3)),
                ('overtime_rate_override', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('effective_from', models.DateTimeField()),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('ended', 'Ended'), ('cancelled', 'Cancelled')], default='active', max_length=16)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compensations', to='employees.employee')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'employees_employeecompensation',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['company', 'employment_status'], name='employees_e_company_d090a8_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['company', 'user'], name='employees_e_company_5022a7_idx'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('company', 'user'), name='uniq_employee_user_per_company'),
        ),
        migrations.AddIndex(
            model_name='employeeassignment',
            index=models.Index(fields=['company', 'employee_code', 'effective_from'], name='employees_e_company_b2ab41_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeassignment',
            index=models.Index(fields=['company', 'employee', 'effective_from'], name='employees_e_company_3f0855_idx'),
        ),
        migrations.AddConstraint(
            model_name='employeeassignment',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gt', models.F('effective_from')), _connector='OR'), name='assignment_period_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='employeeassignment',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status', 'cancelled'), _negated=True), expressions=[('company', '='), ('employee', '='), (common.db.TstzRange('effective_from', 'effective_to', django.contrib.postgres.fields.ranges.RangeBoundary()), '&&')], name='excl_assignment_overlap_per_employee'),
        ),
        migrations.AddConstraint(
            model_name='employeeassignment',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status', 'cancelled'), _negated=True), expressions=[('company', '='), ('employee_code', '='), (common.db.TstzRange('effective_from', 'effective_to', django.contrib.postgres.fields.ranges.RangeBoundary()), '&&')], name='excl_employee_code_overlap_per_company'),
        ),
        migrations.AddIndex(
            model_name='employeecompensation',
            index=models.Index(fields=['company', 'employee', 'effective_from'], name='employees_e_company_3d5f18_idx'),
        ),
        migrations.AddConstraint(
            model_name='employeecompensation',
            constraint=models.CheckConstraint(condition=models.Q(('base_rate__gt', 0)), name='compensation_base_rate_positive'),
        ),
        migrations.AddConstraint(
            model_name='employeecompensation',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gt', models.F('effective_from')), _connector='OR'), name='compensation_period_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='employeecompensation',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status__in', ('active', 'ended'))), expressions=[('company', '='), ('employee', '='), (common.db.TstzRange('effective_from', 'effective_to', django.contrib.postgres.fields.ranges.RangeBoundary()), '&&')], name='excl_compensation_overlap_per_employee'),
        ),
    ]
