# Generated by Django 6.1.1 on 2026-09-19 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_assignment_company_department'),
        ('organization', '0004_designation_independent_of_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeassignment',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='organization.department'),
        ),
        migrations.AlterField(
            model_name='employeeassignment',
            name='designation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='organization.designation'),
        ),
    ]
