# Generated by Django 6.1.1 on 2026-09-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employeeassignment_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='hide_from_reports',
            field=models.BooleanField(default=False),
        ),
    ]
