# Generated by Django 6.1.1 on 2026-09-27 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_education_and_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='no_overtime_from',
            field=models.DateField(blank=True, null=True),
        ),
    ]
