from django.urls import path

from api.v1.employees import profile_views as pv
from api.v1.employees import views

urlpatterns = [
    path("employees", views.EmployeeListView.as_view(), name="employees"),
    path("employees/choices", views.ChoicesView.as_view(), name="employee_choices"),
    path("employees/export", views.EmployeeExportView.as_view(), name="employee_export"),
    path("employees/import", pv.ImportView.as_view(), name="employee_import"),
    path("employees/import/demo-file", pv.ImportDemoView.as_view(), name="employee_import_demo"),
    path("employees/<int:employee_id>", views.EmployeeDetailView.as_view(), name="employee"),
    path("employees/<int:employee_id>/history", views.HistoryView.as_view(),
         name="employee_history"),
    path("employees/<int:employee_id>/personal", views.PersonalView.as_view(),
         name="employee_personal"),
    path("employees/<int:employee_id>/placement", views.PlacementView.as_view(),
         name="employee_placement"),
    path("employees/<int:employee_id>/salary", views.SalaryView.as_view(),
         name="employee_salary"),
    path("employees/<int:employee_id>/line-manager", views.LineManagerView.as_view(),
         name="employee_line_manager"),
    path("employees/<int:employee_id>/end-employment", views.EndEmploymentView.as_view(),
         name="employee_end"),
    path("employees/<int:employee_id>/inactive", views.InactiveView.as_view(),
         name="employee_inactive"),
    path("employees/<int:employee_id>/active", views.ActiveView.as_view(),
         name="employee_active"),
    path("employees/<int:employee_id>/photo", pv.PhotoView.as_view(), name="employee_photo"),
    path("employees/<int:employee_id>/education", pv.EducationListView.as_view(),
         name="employee_education"),
    path("employees/<int:employee_id>/education/<int:row_id>", pv.EducationRowView.as_view(),
         name="employee_education_row"),
    path("employees/<int:employee_id>/documents", pv.DocumentListView.as_view(),
         name="employee_documents"),
    path("employees/<int:employee_id>/documents/<int:document_id>", pv.DocumentView.as_view(),
         name="employee_document"),
    path("employees/<int:employee_id>/login", pv.LoginView.as_view(), name="employee_login"),
    path("employees/<int:employee_id>/login/password", pv.LoginPasswordView.as_view(),
         name="employee_login_password"),
    path("employees/<int:employee_id>/login/disable", pv.LoginDisableView.as_view(),
         name="employee_login_disable"),
    path("employees/<int:employee_id>/login/enable", pv.LoginEnableView.as_view(),
         name="employee_login_enable"),
    path("employees/<int:employee_id>/leave-policy", pv.LeavePolicyView.as_view(),
         name="employee_leave_policy"),
    path("employees/<int:employee_id>/leave-adjustments", pv.LeaveAdjustmentView.as_view(),
         name="employee_leave_adjust"),
    path("employees/<int:employee_id>/overtime", pv.OvertimeView.as_view(),
         name="employee_overtime"),
    path("employees/<int:employee_id>/report-visibility", pv.ReportVisibilityView.as_view(),
         name="employee_report_visibility"),
    path("employees/<int:employee_id>/reports", pv.ReportsView.as_view(), name="employee_reports"),
    path("employees/<int:employee_id>/devices", pv.DeviceLinksView.as_view(),
         name="employee_devices"),
    path("employees/<int:employee_id>/devices/<int:enrollment_id>", pv.DeviceLinkView.as_view(),
         name="employee_device"),
]
