# Generated by Django 6.1.1 on 2026-09-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_feature_companyfeature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='country_code',
            field=models.CharField(blank=True, default='BD', max_length=2),
        ),
        migrations.AlterField(
            model_name='company',
            name='currency',
            field=models.CharField(default='BDT', max_length=3),
        ),
        migrations.AlterField(
            model_name='company',
            name='timezone',
            field=models.CharField(default='Asia/Dhaka', max_length=64),
        ),
    ]
