# Generated by Django 6.1.1 on 2026-09-08 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_company_code_sequence'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='feature',
            table='module',
        ),
    ]
