# Generated by Django 6.1.1 on 2026-09-16 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_alter_feature_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='contact_person',
            field=models.CharField(blank=True, db_default='', max_length=120),
        ),
    ]
