# Generated by Django 6.1.1 on 2026-10-04 07:50

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caller', models.CharField(max_length=80)),
                ('key', models.CharField(max_length=128)),
                ('request_hash', models.CharField(max_length=64)),
                ('status_code', models.PositiveSmallIntegerField()),
                ('response_body', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'api_idempotency_record',
                'indexes': [models.Index(fields=['created_at'], name='api_idempot_created_fb8bf6_idx')],
                'constraints': [models.UniqueConstraint(fields=('caller', 'key'), name='uniq_api_idempotency_caller_key')],
            },
        ),
    ]
