# Generated by Django 6.1.1 on 2026-10-04 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_idempotency_record'),
        ('tenants', '0006_company_contact_person'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(db_index=True, max_length=254)),
                ('ip', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('succeeded', models.BooleanField(default=False)),
                ('reason', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'api_login_attempt',
            },
        ),
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('secret_encrypted', models.TextField()),
                ('previous_secret_encrypted', models.TextField(blank=True)),
                ('previous_valid_until', models.DateTimeField(blank=True, null=True)),
                ('scopes', models.JSONField(default=list)),
                ('allowed_ips', models.JSONField(blank=True, default=list)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='tenants.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_key',
            },
        ),
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_password_reset',
            },
        ),
        migrations.CreateModel(
            name='TwoStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_encrypted', models.TextField()),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('recovery_hashes', models.JSONField(blank=True, default=list)),
                ('last_used_step', models.BigIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='api_two_step', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_two_step',
            },
        ),
        migrations.CreateModel(
            name='UsedNonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=40)),
                ('nonce', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'api_used_nonce',
                'constraints': [models.UniqueConstraint(fields=('owner', 'nonce'), name='uniq_api_nonce_owner')],
            },
        ),
        migrations.CreateModel(
            name='ApiSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(max_length=40, unique=True)),
                ('client_type', models.CharField(choices=[('mobile', 'Mobile app'), ('desktop', 'Desktop app'), ('web', 'Web frontend (cookies)')], max_length=10)),
                ('device_name', models.CharField(blank=True, max_length=120)),
                ('state', models.CharField(choices=[('two_step', 'Waiting for the two-step code'), ('active', 'Active'), ('ended', 'Ended')], default='active', max_length=10)),
                ('needs_two_step_setup', models.BooleanField(default=False)),
                ('access_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('access_expires_at', models.DateTimeField(blank=True, null=True)),
                ('refresh_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('refresh_expires_at', models.DateTimeField(blank=True, null=True)),
                ('previous_refresh_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('rotated_at', models.DateTimeField(blank=True, null=True)),
                ('challenge_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('challenge_expires_at', models.DateTimeField(blank=True, null=True)),
                ('signing_secret_encrypted', models.TextField(blank=True)),
                ('password_fingerprint', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('last_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('ended_reason', models.CharField(blank=True, max_length=120)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_session',
                'indexes': [models.Index(fields=['user', 'state'], name='api_session_user_id_1cd3f6_idx')],
            },
        ),
    ]
