# Generated by Django 6.1.1 on 2026-10-04 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_logins_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='apisession',
            name='email_code_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apisession',
            name='email_code_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='apisession',
            name='email_code_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apisession',
            name='email_code_tries',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='twostep',
            name='method',
            field=models.CharField(choices=[('app', 'Authenticator app'), ('email', 'Code by email')], default='app', max_length=10),
        ),
        migrations.AddField(
            model_name='twostep',
            name='pending_method',
            field=models.CharField(blank=True, choices=[('app', 'Authenticator app'), ('email', 'Code by email')], max_length=10),
        ),
        migrations.AddField(
            model_name='twostep',
            name='pending_secret_encrypted',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='twostep',
            name='secret_encrypted',
            field=models.TextField(blank=True),
        ),
    ]
