# Generated by Django 6.1.1 on 2026-10-05 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_two_step_app_with_email_backup'),
    ]

    operations = [
        migrations.AddField(
            model_name='twostep',
            name='method',
            field=models.CharField(choices=[('app', 'Authenticator app'), ('email', 'Code by email')], default='app', max_length=10),
        ),
        migrations.AddField(
            model_name='twostep',
            name='pending_method',
            field=models.CharField(blank=True, choices=[('app', 'Authenticator app'), ('email', 'Code by email')], max_length=10),
        ),
    ]
