# Generated by Django 6.1.1 on 2026-09-07 06:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_companymembership_allowed_branches_and_more'),
        ('tenants', '0002_feature_companyfeature'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_type', models.CharField(choices=[('user', 'User'), ('system', 'System'), ('device', 'Device'), ('background_job', 'Background job'), ('root_admin', 'Platform owner')], max_length=20)),
                ('action', models.CharField(max_length=100)),
                ('object_app', models.CharField(max_length=64)),
                ('object_model', models.CharField(max_length=64)),
                ('object_id', models.CharField(max_length=64)),
                ('object_public_id', models.CharField(blank=True, max_length=64)),
                ('object_display', models.CharField(max_length=255)),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('correlation_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('before_data', models.JSONField(blank=True, default=dict)),
                ('after_data', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('integrity_hash', models.CharField(blank=True, max_length=128)),
                ('previous_hash', models.CharField(blank=True, max_length=128)),
                ('actor_membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.companymembership')),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tenants.company')),
            ],
            options={
                'ordering': ('-occurred_at', '-pk'),
                'indexes': [models.Index(fields=['company', 'occurred_at'], name='audit_company_time'), models.Index(fields=['company', 'object_model', 'object_id', 'occurred_at'], name='audit_company_object_time')],
            },
        ),
    ]
