# Generated by Django 6.1.1 on 2026-09-06 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_companymembership'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymembership',
            name='allowed_branches',
            field=models.ManyToManyField(blank=True, related_name='scoped_memberships', to='organization.branch'),
        ),
        migrations.AddField(
            model_name='companymembership',
            name='allowed_departments',
            field=models.ManyToManyField(blank=True, related_name='scoped_memberships', to='organization.department'),
        ),
        migrations.AddField(
            model_name='companymembership',
            name='last_access_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
