# Generated by Django 6.1.1 on 2026-09-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_companymembership_allowed_branches_and_more'),
        ('organization', '0001_initial'),
        ('tenants', '0003_alter_company_country_code_alter_company_currency_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='companymembership',
            constraint=models.UniqueConstraint(condition=models.Q(('role__in', ['owner', 'company_admin']), models.Q(('status', 'ended'), _negated=True)), fields=('company',), name='uniq_current_company_administrator'),
        ),
        migrations.AddConstraint(
            model_name='companymembership',
            constraint=models.UniqueConstraint(condition=models.Q(('role__in', ['owner', 'company_admin']), models.Q(('status', 'ended'), _negated=True)), fields=('user',), name='uniq_current_administrator_company'),
        ),
    ]
