# Generated by Django 6.1.1 on 2026-09-19 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_membership_company_department_scope'),
        ('organization', '0004_designation_independent_of_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companymembership',
            name='allowed_departments',
        ),
        migrations.AddField(
            model_name='companymembership',
            name='allowed_departments',
            field=models.ManyToManyField(blank=True, related_name='scoped_memberships', to='organization.department'),
        ),
    ]
