"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import sys
from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Configuration is read from the environment (12-factor). Declare defaults and
# types here, then load a project-root .env if present. .env is git-ignored and
# holds real secrets; .env.example documents every key. See docs Lesson 3.
env = environ.Env(
    DEBUG=(bool, False),
    # Only the loopback names belong in a shared default. A developer's own
    # tunnel hostname is personal to their machine and goes in their .env,
    # so a teammate never inherits someone else's address.
    ALLOWED_HOSTS=(list, ['localhost', '127.0.0.1']),
    DB_CONN_MAX_AGE=(int, 60),
    # Origins allowed to submit browser forms. A biometric device reaches this
    # server through a tunnel hostname during development; the *device*
    # endpoints are CSRF-exempt and device-authenticated, but the admin screens
    # served over that same hostname still need it. Devices push inbound, so
    # localhost is not reachable from them (see docs/DEVICE_SETUP.md).
    CSRF_TRUSTED_ORIGINS=(list, ['https://*.ngrok-free.dev', 'https://*.ngrok-free.app']),
)
environ.Env.read_env(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# The default is a development-only key; set SECRET_KEY in .env for real use.
SECRET_KEY = env(
    'SECRET_KEY',
    default='django-insecure-r3zq3+zrj(6(3ql07p*laww+rcpd-kzt8eqk09)$pal^9@p#og',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

ALLOWED_HOSTS = env('ALLOWED_HOSTS')

CSRF_TRUSTED_ORIGINS = env('CSRF_TRUSTED_ORIGINS')

# Encrypts the fingerprint/face templates the server keeps so it can copy them
# to a company's other devices of the same model (devices/services/templates.py).
# A Fernet key; blank means templates are refused, never stored in plain text.
BIOMETRIC_TEMPLATE_KEY = env('BIOMETRIC_TEMPLATE_KEY', default='')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Enables PostgreSQL-only features (ExclusionConstraint for non-overlapping
    # effective-dated periods). Framework app: adds no models or tables.
    'django.contrib.postgres',
    # Domain apps (12) — order roughly follows dependency/read order.
    'accounts',
    'tenants',
    'organization',
    'employees',
    'access_control',
    'scheduling',
    'devices',
    'attendance',
    'leaves',
    'payroll',
    'reports',
    'subscriptions',
    'auditlog',
    # The ERP webhook: attendance pushed to a company's own system.
    'webhooks',
    # The REST API (docs/api/00-PLAN.md): the panels' functions for apps,
    # frontends and the ERP. Calls the same services the panels use.
    'rest_framework',
    'drf_spectacular',
    'corsheaders',
    'api',
    # Shared presentation app (no domain models/tables).
    'base_template',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # Which web frontends may call the API from a browser (only /api/).
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # Must follow AuthenticationMiddleware: it needs request.user to resolve the
    # active company, and it sets/clears the tenant context for the request.
    'common.middleware.TenantMiddleware',
    # Employees and branch managers stay on their own pages (common/middleware.py).
    'common.middleware.SelfServiceGate',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # Active company + switchable memberships for the shell.
                'base_template.context_processors.shell',
            ],
        },
    },
]

# Tests only. PBKDF2 is deliberately slow — about a second per call on this
# hardware — which is right in production and pointless for the hundreds of
# throwaway users the suite creates. Swapping it for MD5 under `manage.py test`
# cut the run by roughly a third. Production is untouched: this branch cannot
# be reached by a real server process.
if sys.argv[1:2] == ['test']:
    PASSWORD_HASHERS = ['django.contrib.auth.hashers.MD5PasswordHasher']

# The ERP webhook sends in a background thread so a device or a page never
# waits for a company's ERP. Tests send in the foreground, by calling it.
WEBHOOK_SEND_IN_BACKGROUND = sys.argv[1:2] != ['test']
# "Load employees onto this device" prepares people in a background thread
# (250+ in one request ran past the server's time limit). Tests run it inline.
DEVICE_LOAD_IN_BACKGROUND = sys.argv[1:2] != ['test']


WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

# PostgreSQL is the authoritative engine (see docs/IMPLEMENTATION_ROADMAP.md P0).
# Discrete env vars (read via django-environ) so the password sits on its own
# line and needs no URL percent-encoding for special characters. No secret is
# committed; the empty-password default only works once .env supplies a real one.
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env('POSTGRES_DB', default='attendance_system'),
        'USER': env('POSTGRES_USER', default='attendance'),
        'PASSWORD': env('POSTGRES_PASSWORD', default=''),
        'HOST': env('POSTGRES_HOST', default='localhost'),
        'PORT': env('POSTGRES_PORT', default='5432'),
        # Reuse connections for up to 60s instead of opening one per request.
        'CONN_MAX_AGE': env('DB_CONN_MAX_AGE'),
    },
}


# Authentication
# Custom concrete user model, locked in before the first migration.
# Runtime code must resolve it via django.contrib.auth.get_user_model();
# relations must reference settings.AUTH_USER_MODEL, never accounts.User directly.
AUTH_USER_MODEL = 'accounts.User'

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
# Where `collectstatic` gathers files for a deployed server. Git-ignored.
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Uploaded files (today: a company's logo). Served by the web server in
# production; by Django itself only while DEBUG is on (config/urls.py).
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Cache-busting: every static URL changes when its file changes, so a browser
# never keeps an old CSS/JS file after an update (no more Ctrl+F5). Hashed
# file names when deployed, `?v=<hash>` in development and tests — see
# base_template/staticfiles.py.
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'base_template.staticfiles.VersionedStaticFilesStorage',
    },
}


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

# Nothing is sent until a mail server is set in .env. Until then mail goes to
# the console and the pages that send it say email is not set up, rather than
# reporting success for a message nobody receives (payroll/payslip_email.py).
# Django 6 refuses the old EMAIL_* settings beside MAILERS, so these stay
# private to this module; MAIL_CONFIGURED is what the project asks.
_email_host = env('EMAIL_HOST', default='')
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', default='')
MAIL_CONFIGURED = bool(_email_host and DEFAULT_FROM_EMAIL)

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.smtp.EmailBackend',
        'OPTIONS': {
            'host': _email_host,
            'port': env.int('EMAIL_PORT', default=587),
            'username': env('EMAIL_HOST_USER', default=''),
            'password': env('EMAIL_HOST_PASSWORD', default=''),
            'use_tls': env.bool('EMAIL_USE_TLS', default=True),
            'timeout': 20,
        },
    } if _email_host else {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}


# A rejected CSRF token is usually a stale tab, not an attack: Django
# rotates the token on login, so a page opened beforehand still carries the
# old one. The request is still refused; this only replaces the bare
# "Forbidden (403)" wall with a page that says how to recover.
CSRF_FAILURE_VIEW = 'base_template.views.csrf_failure'


# --- The REST API (docs/api/00-PLAN.md) -------------------------------------
# Deny by default: an endpoint is open only to whoever it names. JSON only;
# errors in one shape (api/core/errors.py); lists paged, 100 at most.
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': ['api.core.auth.ApiAuthentication'],
    'DEFAULT_PERMISSION_CLASSES': ['api.core.permissions.DenyAll'],
    'DEFAULT_RENDERER_CLASSES': ['rest_framework.renderers.JSONRenderer'],
    'DEFAULT_PARSER_CLASSES': ['rest_framework.parsers.JSONParser'],
    'DEFAULT_PAGINATION_CLASS': 'api.core.pagination.StandardPagination',
    'DEFAULT_THROTTLE_CLASSES': ['api.core.throttling.ApiRateThrottle'],
    'DEFAULT_THROTTLE_RATES': {
        # A scope per kind of endpoint; each endpoint's page shows its rate.
        'public': '60/minute',
        'read': '300/minute',
        'write': '120/minute',
        'login': '10/minute',
    },
    'EXCEPTION_HANDLER': 'api.core.errors.exception_handler',
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'UNAUTHENTICATED_USER': None,
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Attendance Management API',
    'DESCRIPTION': 'The company, branch and employee panels as an API. '
                   'Full documentation: /api/docs/',
    'VERSION': 'v1',
    'SERVE_INCLUDE_SCHEMA': False,
    'SCHEMA_PATH_PREFIX': r'/api/v1',
    # Choice lists that share a field name ("status") get names of their own.
    'ENUM_NAME_OVERRIDES': {
        'ActiveStatusEnum': 'common.choices.ActiveStatus',
        'EndingStatusEnum': 'organization.employee_detail_services.ENDING_STATUSES',
    },
}

# Rate limits are counted in the database, so they hold across every
# server worker (a per-process cache would give each worker its own count).
# Run `python manage.py createcachetable` once when deploying.
CACHES = {
    'default': {'BACKEND': 'django.core.cache.backends.locmem.LocMemCache'},
    'api': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'api_cache',
    },
}

# Browser frontends allowed to call the API: comma-separated origins in .env,
# e.g. API_CORS_ORIGINS=https://app.example.com. Empty: none.
CORS_ALLOWED_ORIGINS = env.list('API_CORS_ORIGINS', default=[])
CORS_URLS_REGEX = r'^/api/.*$'
CORS_ALLOW_CREDENTIALS = True
CORS_EXPOSE_HEADERS = ['Retry-After', 'X-Request-Id']
CORS_ALLOW_HEADERS = (
    'accept', 'authorization', 'content-type', 'x-csrftoken', 'x-company',
    'idempotency-key', 'x-key-id', 'x-timestamp', 'x-nonce', 'x-signature',
)

# Logging in to the API (docs/api/00-PLAN.md, Part 2).
API_ACCESS_MINUTES = env.int('API_ACCESS_MINUTES', default=10)
API_REFRESH_DAYS = env.int('API_REFRESH_DAYS', default=30)
# Proxies in front of the server (nginx on the live server: 1), so the API
# reads the caller's real address from X-Forwarded-For - and only the part
# our own proxy added. 0: the connection's address.
API_PROXY_COUNT = env.int('API_PROXY_COUNT', default=0)
# Web frontend cookies: Secure unless DEBUG; SameSite Strict, or None when the
# frontend is on another site (then HTTPS is required).
API_COOKIE_SECURE = env.bool('API_COOKIE_SECURE', default=not DEBUG)
API_COOKIE_SAMESITE = env('API_COOKIE_SAMESITE', default='Strict')
# Password reset email: the frontend's page, with {token} where the code goes,
# e.g. https://app.example.com/reset?token={token}. Empty: the code is emailed.
API_PASSWORD_RESET_URL = env('API_PASSWORD_RESET_URL', default='')
# The API sends files inside JSON (base64, about a third larger), so a 2 MB
# logo arrives as about 2.7 MB - over Django's 2.5 MB default for a request
# body. Behind nginx, client_max_body_size must allow it too.
DATA_UPLOAD_MAX_MEMORY_SIZE = 4 * 1024 * 1024
# A browser frontend allowed by CORS may also send the CSRF token.
CSRF_TRUSTED_ORIGINS = list(CSRF_TRUSTED_ORIGINS) + list(CORS_ALLOWED_ORIGINS)

# Argon2 first: the strongest of Django's password hashers. Passwords saved
# with the older ones upgrade on their next login. Tests use a fast hasher.
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.ScryptPasswordHasher',
]
if sys.argv[1:2] == ['test']:
    PASSWORD_HASHERS = ['django.contrib.auth.hashers.MD5PasswordHasher'] + PASSWORD_HASHERS
