# Generated by Django 6.1.1 on 2026-09-12 10:25

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_assignment_company_department'),
        ('tenants', '0005_alter_feature_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('action_type', models.CharField(choices=[('new', 'New'), ('amend', 'Amend'), ('cancel', 'Cancel')], default='new', max_length=16)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('cancelled', 'Cancelled'), ('partially_cancelled', 'Partially cancelled')], default='draft', max_length=24)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('decision_snapshot', models.JSONField(blank=True, default=dict)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leave_requests', to='employees.employee')),
                ('submission_assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leave_requests', to='employees.employeeassignment')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_leave_requests', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payroll_leave_request',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRequestSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('duration_type', models.CharField(choices=[('full_day', 'Full day'), ('half_day', 'Half day'), ('hourly', 'Hourly')], default='full_day', max_length=16)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('half_day_part', models.CharField(blank=True, max_length=16)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('timezone', models.CharField(blank=True, max_length=64)),
                ('requested_units', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('requested_minutes', models.PositiveIntegerField(default=0)),
                ('requested_pay_type', models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')], max_length=16)),
                ('requested_pay_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('sequence_number', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('active', 'Active'), ('superseded', 'Superseded'), ('cancelled', 'Cancelled')], default='active', max_length=16)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.company')),
                ('leave_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='segments', to='leaves.leaverequest')),
            ],
            options={
                'db_table': 'payroll_leave_request_segment',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='LeaveDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work_date', models.DateField()),
                ('covered_start_at', models.DateTimeField()),
                ('covered_end_at', models.DateTimeField()),
                ('scheduled_minutes_snapshot', models.PositiveIntegerField()),
                ('leave_minutes', models.PositiveIntegerField()),
                ('balance_units', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ('approved_pay_type', models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')], max_length=16)),
                ('approved_pay_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('calendar_snapshot', models.JSONField(blank=True, default=dict)),
                ('shift_snapshot', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('approved', 'Approved'), ('consumed', 'Consumed'), ('cancelled', 'Cancelled'), ('reversed', 'Reversed')], default='approved', max_length=16)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leave_days', to='employees.employee')),
                ('employee_assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leave_days', to='employees.employeeassignment')),
                ('request_segment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='days', to='leaves.leaverequestsegment')),
            ],
            options={
                'db_table': 'payroll_leave_day',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('default_balance_unit', models.CharField(choices=[('days', 'Days'), ('minutes', 'Minutes')], default='days', max_length=16)),
                ('requires_attachment_by_default', models.BooleanField(default=False)),
                ('color', models.CharField(blank=True, max_length=16)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=16)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payroll_leave_type',
                'ordering': ('name',),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='leaverequestsegment',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='segments', to='leaves.leavetype'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['company', 'employee', 'status'], name='payroll_lea_company_c571a6_idx'),
        ),
        migrations.AddIndex(
            model_name='leaveday',
            index=models.Index(fields=['company', 'employee', 'work_date'], name='payroll_lea_company_ea9c14_idx'),
        ),
        migrations.AddIndex(
            model_name='leaveday',
            index=models.Index(fields=['company', 'work_date'], name='payroll_lea_company_bafb40_idx'),
        ),
        migrations.AddConstraint(
            model_name='leaveday',
            constraint=models.CheckConstraint(condition=models.Q(('covered_end_at__gt', models.F('covered_start_at'))), name='leave_day_covered_interval_positive'),
        ),
        migrations.AddConstraint(
            model_name='leaveday',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['reserved', 'approved', 'consumed'])), fields=('company', 'employee', 'work_date'), name='uniq_live_leave_day_per_employee_date'),
        ),
        migrations.AddConstraint(
            model_name='leaveday',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('approved_pay_percentage', 100), ('approved_pay_type', 'paid')), models.Q(('approved_pay_percentage', 0), ('approved_pay_type', 'unpaid')), _connector='OR'), name='leave_day_pay_type_matches_percentage'),
        ),
        migrations.AddConstraint(
            model_name='leavetype',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uniq_leave_type_code_per_company'),
        ),
        migrations.AddConstraint(
            model_name='leaverequestsegment',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='leave_segment_end_not_before_start'),
        ),
    ]
