# Generated by Django 6.1.1 on 2026-09-27 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0002_leave_type_days_per_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='leave_documents/'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='attachment_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
