# Generated by Django 6.1.1 on 2026-09-27 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_profile_actions'),
        ('leaves', '0003_leave_attachment'),
        ('tenants', '0006_company_contact_person'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='leaveday',
            name='leave_day_pay_type_matches_percentage',
        ),
        migrations.AlterField(
            model_name='leaveday',
            name='approved_pay_type',
            field=models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid'), ('partial', 'Part paid')], max_length=16),
        ),
        migrations.AlterField(
            model_name='leaverequestsegment',
            name='requested_pay_type',
            field=models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid'), ('partial', 'Part paid')], max_length=16),
        ),
        migrations.AddConstraint(
            model_name='leaveday',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('approved_pay_percentage', 100), ('approved_pay_type', 'paid')), models.Q(('approved_pay_percentage', 0), ('approved_pay_type', 'unpaid')), models.Q(('approved_pay_percentage__gte', 1), ('approved_pay_percentage__lte', 99), ('approved_pay_type', 'partial')), _connector='OR'), name='leave_day_pay_type_matches_percentage'),
        ),
    ]
