# Generated by Django 6.1.1 on 2026-09-27 08:59

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_profile_actions'),
        ('leaves', '0004_leave_shapes'),
        ('tenants', '0006_company_contact_person'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeavePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_default', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=16)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'leaves_policy',
                'ordering': ('name',),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeLeavePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_policies', to='employees.employee')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='leaves.leavepolicy')),
            ],
            options={
                'db_table': 'leaves_employee_policy',
                'ordering': ('employee', 'effective_from'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='LeavePolicyVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveIntegerField()),
                ('effective_from', models.DateField()),
                ('note', models.CharField(blank=True, max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='leaves.leavepolicy')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'leaves_policy_version',
                'ordering': ('policy', 'effective_from'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='LeavePolicyRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('days_per_year', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('accrual', models.CharField(choices=[('yearly', 'All at the start of the year'), ('monthly', 'A twelfth each month')], default='yearly', max_length=16)),
                ('carry_forward_days', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('carry_forward_expires_months', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('allow_half_day', models.BooleanField(default=True)),
                ('allow_hourly', models.BooleanField(default=True)),
                ('allow_negative', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.company')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rules', to='leaves.leavetype')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='leaves.leavepolicyversion')),
            ],
            options={
                'db_table': 'leaves_policy_rule',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='LeaveLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveSmallIntegerField()),
                ('entry_date', models.DateField()),
                ('kind', models.CharField(choices=[('accrual', 'Earned'), ('carry_forward', 'Carried forward'), ('expiry', 'Carried days expired'), ('adjustment', 'Adjusted by hand')], max_length=16)),
                ('units', models.DecimalField(decimal_places=2, max_digits=7)),
                ('period_key', models.CharField(blank=True, max_length=32)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_ledger', to='employees.employee')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger', to='leaves.leavetype')),
                ('policy_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='leaves.leavepolicyversion')),
            ],
            options={
                'db_table': 'leaves_ledger_entry',
                'ordering': ('entry_date', 'pk'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='leavepolicy',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uniq_leave_policy_code_per_company'),
        ),
        migrations.AddConstraint(
            model_name='leavepolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('company',), name='uniq_default_leave_policy_per_company'),
        ),
        migrations.AddConstraint(
            model_name='employeeleavepolicy',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='leave_employee_policy_end_not_before_start'),
        ),
        migrations.AddConstraint(
            model_name='leavepolicyversion',
            constraint=models.UniqueConstraint(fields=('policy', 'number'), name='uniq_leave_policy_version_number'),
        ),
        migrations.AddConstraint(
            model_name='leavepolicyversion',
            constraint=models.UniqueConstraint(fields=('policy', 'effective_from'), name='uniq_leave_policy_version_start'),
        ),
        migrations.AddConstraint(
            model_name='leavepolicyrule',
            constraint=models.UniqueConstraint(fields=('version', 'leave_type'), name='uniq_leave_policy_rule_per_type'),
        ),
        migrations.AddIndex(
            model_name='leaveledgerentry',
            index=models.Index(fields=['company', 'employee', 'leave_type', 'year'], name='leaves_ledg_company_69f0a4_idx'),
        ),
        migrations.AddConstraint(
            model_name='leaveledgerentry',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'adjustment'), _negated=True), fields=('company', 'employee', 'leave_type', 'kind', 'period_key'), name='uniq_automatic_leave_ledger_entry'),
        ),
    ]
