# Generated by Django 6.1.1 on 2026-09-19 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0002_department_permission'),
        ('organization', '0004_designation_independent_of_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentpermission',
            name='company_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permission_rules', to='organization.department'),
        ),
        migrations.AlterField(
            model_name='designationpermission',
            name='designation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permission_rules', to='organization.designation'),
        ),
        migrations.RemoveField(
            model_name='employeepermissionoverride',
            name='allowed_departments',
        ),
        migrations.AddField(
            model_name='employeepermissionoverride',
            name='allowed_departments',
            field=models.ManyToManyField(blank=True, related_name='permission_overrides', to='organization.department'),
        ),
    ]
