# Generated by Django 6.1.1 on 2026-09-13 10:33

import common.db
import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
import django.db.models.manager
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
        ('tenants', '0005_alter_feature_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollPolicyVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Salary rules', max_length=120)),
                ('code', models.CharField(default='SALARY', max_length=32)),
                ('version_number', models.PositiveIntegerField()),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('monthly_divisor', models.DecimalField(decimal_places=6, default=Decimal('30'), max_digits=18)),
                ('monthly_proration_method', models.CharField(choices=[('fixed_30', 'Monthly salary ÷ a fixed number of days'), ('calendar_days', 'Monthly salary ÷ days in that month'), ('scheduled_workdays', 'Monthly salary ÷ working days in that month'), ('none', 'No per-day value')], default='fixed_30', max_length=24)),
                ('daily_rate_method', models.CharField(choices=[('explicit_rate', "The employee's own daily rate"), ('monthly_divisor', 'Monthly salary ÷ the fixed number of days'), ('scheduled_workdays', 'Monthly salary ÷ working days')], default='explicit_rate', max_length=24)),
                ('hourly_rate_method', models.CharField(choices=[('explicit_rate', "The employee's own hourly rate"), ('daily_scheduled_hours', 'Daily rate ÷ shift hours'), ('monthly_standard_hours', 'Monthly salary ÷ standard monthly hours')], default='explicit_rate', max_length=24)),
                ('joining_leaving_proration_method', models.CharField(choices=[('fixed_30', 'Monthly salary ÷ a fixed number of days'), ('calendar_days', 'Monthly salary ÷ days in that month'), ('scheduled_workdays', 'Monthly salary ÷ working days in that month'), ('none', 'No per-day value')], default='calendar_days', max_length=24)),
                ('absence_deduction_method', models.CharField(choices=[('day_fraction', "By day: an absent day is one day's pay"), ('scheduled_minutes', 'By minutes: every minute short of the shift'), ('rule_only', 'Only through penalty rules')], default='day_fraction', max_length=24)),
                ('paid_leave_treatment', models.CharField(choices=[('full_pay', 'Paid in full')], default='full_pay', max_length=24)),
                ('partial_leave_treatment', models.CharField(choices=[('pay_percentage', 'Paid at the approved percentage')], default='pay_percentage', max_length=24)),
                ('unpaid_leave_treatment', models.CharField(choices=[('deduct', 'Deducted like an absent day')], default='deduct', max_length=24)),
                ('overtime_method', models.CharField(choices=[('none', 'No overtime pay'), ('hourly_rate', 'Hourly rate'), ('fixed_rate', 'Fixed rate'), ('multiplier', 'Hourly rate × multiplier')], default='none', max_length=16)),
                ('overtime_multiplier', models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=18)),
                ('holiday_overtime_multiplier', models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=18)),
                ('overtime_rounding_minutes', models.PositiveIntegerField(default=0)),
                ('minimum_overtime_minutes', models.PositiveIntegerField(default=0)),
                ('require_overtime_approval', models.BooleanField(default=True)),
                ('late_penalty_stacking_method', models.CharField(choices=[('highest_only', 'Highest rule only'), ('cumulative', 'All matching rules'), ('capped', 'All matching rules, capped')], default='highest_only', max_length=16)),
                ('maximum_period_deduction_percent', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('maximum_recovery_percent_of_net', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('money_rounding_mode', models.CharField(choices=[('half_up', 'To the nearest'), ('up', 'Up'), ('down', 'Down')], default='half_up', max_length=16)),
                ('money_rounding_increment', models.DecimalField(decimal_places=6, default=Decimal('0.01'), max_digits=18)),
                ('allow_negative_net_pay', models.BooleanField(default=False)),
                ('calculation_config', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('retired', 'Replaced')], default='draft', max_length=16)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('activated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activated_payroll_policies', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payroll_policy_version',
                'ordering': ('-effective_from', '-version_number'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='policy_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='payroll.payrollpolicyversion'),
        ),
        migrations.CreateModel(
            name='PayrollSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.CharField(default='BDT', max_length=3)),
                ('pay_frequency', models.CharField(choices=[('monthly', 'Monthly')], default='monthly', max_length=16)),
                ('period_start_day', models.PositiveSmallIntegerField(default=1)),
                ('default_pay_day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('monthly_divisor', models.DecimalField(decimal_places=6, default=Decimal('30'), max_digits=18)),
                ('overtime_enabled', models.BooleanField(default=False)),
                ('bonus_enabled', models.BooleanField(default=False)),
                ('advances_enabled', models.BooleanField(default=False)),
                ('loans_enabled', models.BooleanField(default=False)),
                ('auto_include_approved_overtime', models.BooleanField(default=False)),
                ('auto_include_approved_leave', models.BooleanField(default=True)),
                ('require_payroll_approval', models.BooleanField(default=False)),
                ('allow_negative_net_pay', models.BooleanField(default=False)),
                ('default_payment_method', models.CharField(blank=True, max_length=32, null=True)),
                ('settings_version', models.PositiveIntegerField(default=1)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('default_policy_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='payroll.payrollpolicyversion')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payroll_settings',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='payrollpolicyversion',
            constraint=models.UniqueConstraint(fields=('company', 'code', 'version_number'), name='uniq_payroll_policy_version_number'),
        ),
        migrations.AddConstraint(
            model_name='payrollpolicyversion',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status', 'active')), expressions=[('company', '='), ('code', '='), (common.db.DateRange('effective_from', 'effective_to', django.contrib.postgres.fields.ranges.RangeBoundary()), '&&')], name='excl_payroll_policy_active_overlap'),
        ),
        migrations.AddConstraint(
            model_name='payrollpolicyversion',
            constraint=models.CheckConstraint(condition=models.Q(('monthly_divisor__gt', 0)), name='chk_payroll_policy_divisor_positive'),
        ),
        migrations.AddConstraint(
            model_name='payrollpolicyversion',
            constraint=models.CheckConstraint(condition=models.Q(('money_rounding_increment__gt', 0)), name='chk_payroll_policy_rounding_positive'),
        ),
        migrations.AddConstraint(
            model_name='payrollpolicyversion',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gt', models.F('effective_from')), _connector='OR'), name='chk_payroll_policy_period_order'),
        ),
        migrations.AddConstraint(
            model_name='payrollsettings',
            constraint=models.UniqueConstraint(fields=('company',), name='uniq_payroll_settings_company'),
        ),
        migrations.AddConstraint(
            model_name='payrollsettings',
            constraint=models.CheckConstraint(condition=models.Q(('default_pay_day__isnull', True), models.Q(('default_pay_day__gte', 1), ('default_pay_day__lte', 31)), _connector='OR'), name='chk_payroll_settings_pay_day'),
        ),
    ]
