# Generated by Django 6.1.1 on 2026-09-13 11:17

import common.db
import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
import django.db.models.manager
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('employees', '0002_assignment_company_department'),
        ('payroll', '0002_salary_settings'),
        ('tenants', '0005_alter_feature_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollline',
            name='source_type',
            field=models.CharField(blank=True, default='', max_length=24),
        ),
        migrations.CreateModel(
            name='AttendancePenaltyRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=32)),
                ('metric', models.CharField(choices=[('late_minutes', 'Arriving late'), ('early_out_minutes', 'Leaving early'), ('worked_shortfall', 'Working less than the shift'), ('outside_minutes', 'Time out of the office'), ('absence', 'An absent day')], max_length=24)),
                ('operator', models.CharField(choices=[('gte', 'at least'), ('gt', 'more than'), ('lte', 'at most'), ('lt', 'less than'), ('equal', 'exactly')], default='gte', max_length=8)),
                ('threshold_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('required_occurrences', models.PositiveIntegerField(default=1)),
                ('occurrence_mode', models.CharField(choices=[('single_day', 'Every day it happens'), ('within_period', 'Every so many days in a month'), ('consecutive_workdays', 'So many working days in a row'), ('rolling_window', 'So many days within a rolling window')], default='single_day', max_length=24)),
                ('rolling_window_days', models.PositiveIntegerField(blank=True, null=True)),
                ('sequence_break_policy', models.JSONField(blank=True, default=dict)),
                ('deduction_method', models.CharField(choices=[('actual_minutes', 'The minutes themselves'), ('fixed_minutes', 'A fixed number of minutes'), ('day_fraction', "Part of a day's pay"), ('full_day', "A full day's pay"), ('fixed_amount', 'A fixed amount')], max_length=16)),
                ('deduction_value', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('priority', models.IntegerField(default=0)),
                ('exclusive_group', models.CharField(blank=True, max_length=40, null=True)),
                ('stacking_policy', models.CharField(choices=[('highest_only', 'Only the largest in its group'), ('additive', 'Adds up with other rules'), ('capped', 'Adds up, capped per month')], default='additive', max_length=16)),
                ('maximum_deduction', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('retired', 'Replaced')], default='draft', max_length=16)),
                ('version', models.PositiveIntegerField(default=1)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payroll_attendance_penalty_rule',
                'ordering': ('name', '-version'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PenaltyAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('occurrence_identity', models.CharField(max_length=160)),
                ('occurrence_count', models.PositiveIntegerField(default=1)),
                ('deduction_minutes', models.PositiveIntegerField(default=0)),
                ('deduction_day_fraction', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=8)),
                ('deduction_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('currency', models.CharField(default='BDT', max_length=3)),
                ('calculation_details', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('approved', 'Approved'), ('waived', 'Waived'), ('posted', 'Posted'), ('reversed', 'Reversed')], default='proposed', max_length=16)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('calculated_at', models.DateTimeField()),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_penalty_assessments', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='penalty_assessments', to='employees.employee')),
                ('payroll_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='penalty_assessments', to='payroll.payrollperiod')),
                ('penalty_rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='payroll.attendancepenaltyrule')),
                ('reversal_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversals', to='payroll.penaltyassessment')),
            ],
            options={
                'db_table': 'payroll_penalty_assessment',
                'ordering': ('period_start', 'pk'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='payrollline',
            name='penalty_assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payroll_lines', to='payroll.penaltyassessment'),
        ),
        migrations.CreateModel(
            name='PenaltyAssessmentAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence_number', models.PositiveIntegerField(default=1)),
                ('qualifying_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('reason_snapshot', models.JSONField(blank=True, default=dict)),
                ('attendance_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='penalty_links', to='attendance.attendancerecord')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.company')),
                ('penalty_assessment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='days', to='payroll.penaltyassessment')),
            ],
            options={
                'db_table': 'payroll_penalty_assessment_attendance',
                'ordering': ('sequence_number',),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='attendancepenaltyrule',
            constraint=models.UniqueConstraint(fields=('company', 'code', 'version'), name='uniq_penalty_rule_version'),
        ),
        migrations.AddConstraint(
            model_name='attendancepenaltyrule',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status', 'active')), expressions=[('company', '='), ('code', '='), (common.db.DateRange('effective_from', 'effective_to', django.contrib.postgres.fields.ranges.RangeBoundary()), '&&')], name='excl_penalty_rule_active_overlap'),
        ),
        migrations.AddConstraint(
            model_name='attendancepenaltyrule',
            constraint=models.CheckConstraint(condition=models.Q(('required_occurrences__gte', 1)), name='chk_penalty_rule_occurrences'),
        ),
        migrations.AddConstraint(
            model_name='attendancepenaltyrule',
            constraint=models.CheckConstraint(condition=models.Q(('deduction_value__gte', 0)), name='chk_penalty_rule_value_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='attendancepenaltyrule',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gt', models.F('effective_from')), _connector='OR'), name='chk_penalty_rule_period_order'),
        ),
        migrations.AddConstraint(
            model_name='penaltyassessment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'reversed'), _negated=True), fields=('company', 'occurrence_identity'), name='uniq_penalty_occurrence'),
        ),
        migrations.AddConstraint(
            model_name='penaltyassessmentattendance',
            constraint=models.UniqueConstraint(fields=('penalty_assessment', 'attendance_record'), name='uniq_penalty_assessment_day'),
        ),
    ]
