# Generated by Django 6.1.1 on 2026-09-14 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_pairing_sessions'),
        ('payroll', '0003_penalty_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penaltyassessmentattendance',
            name='attendance_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalty_links', to='attendance.attendancerecord'),
        ),
    ]
