# Generated by Django 6.1.1 on 2026-09-14 09:47

import django.db.models.deletion
import django.db.models.manager
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def overtime_defaults_on_saved_rules(apps, schema_editor):
    """Saved rules carry the old placeholders (no overtime pay, 1×).

    Those columns were never on the settings page and nothing read them, so no
    salary was ever worked out with them. Give them the agreed defaults
    (Ajay, 2026-09-14: overtime at 2× the hourly rate) rather than leave every
    company that saved its rules paying no overtime.
    """
    Version = apps.get_model("payroll", "PayrollPolicyVersion")
    Version.objects.filter(overtime_method="none").update(overtime_method="multiplier")
    Version.objects.filter(overtime_multiplier=Decimal("1")).update(overtime_multiplier=Decimal("2"))
    Version.objects.filter(holiday_overtime_multiplier=Decimal("1")).update(
        holiday_overtime_multiplier=Decimal("2")
    )


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_assignment_company_department'),
        ('payroll', '0004_penalty_day_link_cascade'),
        ('tenants', '0005_alter_feature_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollpolicyversion',
            name='holiday_overtime_multiplier',
            field=models.DecimalField(decimal_places=6, default=Decimal('2'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='payrollpolicyversion',
            name='overtime_method',
            field=models.CharField(choices=[('none', 'No overtime pay'), ('hourly_rate', 'Hourly rate'), ('fixed_rate', 'Fixed rate'), ('multiplier', 'Hourly rate × multiplier')], default='multiplier', max_length=16),
        ),
        migrations.AlterField(
            model_name='payrollpolicyversion',
            name='overtime_multiplier',
            field=models.DecimalField(decimal_places=6, default=Decimal('2'), max_digits=18),
        ),
        migrations.CreateModel(
            name='OvertimeDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work_date', models.DateField()),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected')], max_length=16)),
                ('calculated_minutes', models.PositiveIntegerField(default=0)),
                ('approved_minutes', models.PositiveIntegerField(default=0)),
                ('check_out_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('decided_at', models.DateTimeField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.company')),
                ('decided_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overtime_decisions', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='overtime_decisions', to='employees.employee')),
            ],
            options={
                'db_table': 'payroll_overtime_decision',
                'ordering': ('work_date', 'employee_id'),
                'indexes': [models.Index(fields=['company', 'work_date'], name='payroll_ove_company_71ef83_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'employee', 'work_date'), name='uniq_overtime_decision_per_day'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'rejected'), _negated=True), ('approved_minutes', 0), _connector='OR'), name='chk_overtime_rejected_pays_nothing')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RunPython(overtime_defaults_on_saved_rules, migrations.RunPython.noop),
    ]
