# Generated by Django 6.1.1 on 2026-09-23 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0007_payroll_run_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrolladjustment',
            name='source_payroll_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='payroll.payrollperiod'),
        ),
    ]
