# Generated by Django 6.1.1 on 2026-09-23 06:33

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employeeassignment_department_and_more'),
        ('payroll', '0007_payroll_run_approval'),
        ('tenants', '0006_company_contact_person'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('earning', 'Allowance'), ('deduction', 'Deduction')], default='earning', max_length=16)),
                ('method', models.CharField(choices=[('fixed', 'Fixed amount'), ('percent_of_basic', 'Percentage of basic')], default='fixed', max_length=24)),
                ('default_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('default_percent', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=16)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payroll_salary_component',
                'ordering': ('kind', 'name'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeSalaryComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('percent', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled')], default='active', max_length=16)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salary_components', to='employees.employee')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='payroll.salarycomponent')),
            ],
            options={
                'db_table': 'payroll_employee_salary_component',
                'ordering': ('component__name', '-effective_from'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='salarycomponent',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uniq_salary_component_code_per_company'),
        ),
        migrations.AddConstraint(
            model_name='salarycomponent',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='uniq_salary_component_name_per_company'),
        ),
        migrations.AddConstraint(
            model_name='salarycomponent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('default_percent__isnull', True), ('method', 'fixed')), models.Q(('default_amount__isnull', True), ('method', 'percent_of_basic')), _connector='OR'), name='salary_component_amount_matches_method'),
        ),
        migrations.AddIndex(
            model_name='employeesalarycomponent',
            index=models.Index(fields=['company', 'employee', 'effective_from'], name='payroll_emp_company_9c7b6e_idx'),
        ),
        migrations.AddConstraint(
            model_name='employeesalarycomponent',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='employee_component_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='employeesalarycomponent',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'cancelled'), _negated=True), fields=('employee', 'component', 'effective_from'), name='uniq_employee_component_start'),
        ),
    ]
