# Generated by Django 6.1.1 on 2026-09-28 04:06

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_profile_actions'),
        ('leaves', '0005_policies_and_ledger'),
        ('payroll', '0009_correction_source'),
        ('tenants', '0006_company_contact_person'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payrolladjustment',
            name='code',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.CreateModel(
            name='LfaClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cycle_start', models.DateField()),
                ('cycle_end', models.DateField()),
                ('note', models.TextField(blank=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='lfa_documents/')),
                ('document_name', models.CharField(blank=True, max_length=255)),
                ('calculated_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Waiting for approval'), ('approved', 'Approved'), ('paid', 'Paid'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('payment', models.CharField(choices=[('with_salary', 'On the monthly payslip'), ('separately', 'Paid separately')], max_length=16)),
                ('paid_on', models.DateField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.CharField(blank=True, max_length=255)),
                ('settings_snapshot', models.JSONField(blank=True, default=dict)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lfa_claims', to='employees.employee')),
                ('leave_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lfa_claims', to='leaves.leaverequest')),
                ('payroll_adjustment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lfa_claim', to='payroll.payrolladjustment')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payroll_lfa_claim',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['company', 'employee', 'cycle_start'], name='payroll_lfa_company_7c1d4f_idx')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='LfaSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=False)),
                ('name', models.CharField(default='Leave Fare Assistance', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('amount_method', models.CharField(choices=[('fixed', 'A fixed amount'), ('basic_percent', 'A share of monthly basic salary'), ('approver', 'Decided by the approver')], default='basic_percent', max_length=16)),
                ('fixed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('basic_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('min_service_months', models.PositiveSmallIntegerField(default=12)),
                ('probation_eligible', models.BooleanField(default=False)),
                ('cycle', models.CharField(choices=[('calendar_year', 'Once a calendar year (January to December)'), ('service_year', 'Once a service year (from their joining date)')], default='calendar_year', max_length=16)),
                ('claims_per_cycle', models.PositiveSmallIntegerField(default=1)),
                ('requires_leave', models.BooleanField(default=False)),
                ('min_leave_days', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('requires_document', models.BooleanField(default=False)),
                ('prorate_first_cycle', models.BooleanField(default=False)),
                ('payment', models.CharField(choices=[('with_salary', 'On the monthly payslip'), ('separately', 'Paid separately')], default='with_salary', max_length=16)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('leave_types', models.ManyToManyField(blank=True, related_name='+', to='leaves.leavetype')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payroll_lfa_settings',
                'constraints': [models.UniqueConstraint(fields=('company',), name='uniq_lfa_settings_per_company')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
