# Generated by Django 6.1.1 on 2026-09-12 10:49

import django.db.models.deletion
import django.db.models.manager
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_assignment_company_department'),
        ('leaves', '0001_initial'),
        ('organization', '0004_designation_independent_of_department'),
        ('scheduling', '0002_departmentshift_company_department'),
        ('tenants', '0005_alter_feature_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work_date', models.DateField()),
                ('scheduled_start_at', models.DateTimeField()),
                ('scheduled_end_at', models.DateTimeField()),
                ('first_in_at', models.DateTimeField(blank=True, null=True)),
                ('last_out_at', models.DateTimeField(blank=True, null=True)),
                ('worked_minutes', models.PositiveIntegerField(default=0)),
                ('late_minutes', models.PositiveIntegerField(default=0)),
                ('attendance_status', models.CharField(choices=[('present', 'Present'), ('half_day', 'Half day'), ('absent', 'Absent'), ('leave', 'Leave'), ('holiday', 'Holiday'), ('weekly_off', 'Weekly off'), ('incomplete', 'Incomplete')], max_length=16)),
                ('punch_status', models.CharField(choices=[('complete', 'Complete'), ('missing_out', 'Missing OUT'), ('no_punch', 'No punch')], max_length=16)),
                ('payable_fraction', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=4)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('calculated_at', models.DateTimeField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='organization.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='employees.employee')),
                ('employee_assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='employees.employeeassignment')),
                ('leave_day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='leaves.leaveday')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='scheduling.shift')),
            ],
            options={
                'db_table': 'payroll_attendance_record',
                'ordering': ('work_date',),
                'indexes': [models.Index(fields=['company', 'work_date'], name='payroll_att_company_9b8a4b_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'employee', 'work_date'), name='uniq_attendance_record_per_employee_date')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
