# Generated by Django 6.0.7 on 2026-09-13 10:12

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('devices', '0003_device_server_address'),
        ('tenants', '0005_alter_feature_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='break_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='break_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='outside_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='total_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PunchAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence_number', models.PositiveIntegerField()),
                ('event_at', models.DateTimeField()),
                ('interpreted_direction', models.CharField(choices=[('in', 'In'), ('out', 'Out'), ('ignored', 'Ignored'), ('unresolved', 'Unresolved')], default='in', max_length=16)),
                ('label', models.CharField(choices=[('check_in', 'Check-in'), ('break_out', 'Break-out'), ('break_in', 'Break-in'), ('check_out', 'Check-out'), ('ignored', 'Ignored')], default='check_in', max_length=16)),
                ('is_included', models.BooleanField(default=True)),
                ('exclusion_reason', models.CharField(blank=True, choices=[('duplicate', 'Repeat scan'), ('unauthorized_device', 'Device not counted'), ('outside_window', 'Outside the attendance window'), ('superseded', 'Superseded'), ('manual_exclusion', 'Excluded by hand'), ('other', 'Other')], max_length=32)),
                ('interpretation_note', models.CharField(blank=True, max_length=255)),
                ('calculation_version', models.PositiveIntegerField(default=1)),
                ('attendance_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='attendance.attendancerecord')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.company')),
                ('punch_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='devices.punchevent')),
            ],
            options={
                'db_table': 'payroll_punch_allocation',
                'ordering': ('attendance_record', 'sequence_number'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence_number', models.PositiveIntegerField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('worked_minutes', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('complete', 'Complete'), ('missing_in', 'Missing in'), ('missing_out', 'Missing out'), ('invalid', 'Invalid')], default='complete', max_length=16)),
                ('is_manual', models.BooleanField(default=False)),
                ('calculation_version', models.PositiveIntegerField(default=1)),
                ('attendance_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='attendance.attendancerecord')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.company')),
                ('in_allocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opened_sessions', to='attendance.punchallocation')),
                ('out_allocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_sessions', to='attendance.punchallocation')),
            ],
            options={
                'db_table': 'payroll_attendance_session',
                'ordering': ('attendance_record', 'sequence_number'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='punchallocation',
            index=models.Index(fields=['company', 'event_at'], name='payroll_pun_company_0a58ed_idx'),
        ),
        migrations.AddConstraint(
            model_name='punchallocation',
            constraint=models.UniqueConstraint(fields=('attendance_record', 'calculation_version', 'sequence_number'), name='uniq_punch_allocation_sequence'),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['company', 'started_at'], name='payroll_att_company_6620f0_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendancesession',
            constraint=models.UniqueConstraint(fields=('attendance_record', 'calculation_version', 'sequence_number'), name='uniq_attendance_session_sequence'),
        ),
        migrations.AddConstraint(
            model_name='attendancesession',
            constraint=models.CheckConstraint(condition=models.Q(('ended_at__isnull', True), ('started_at__isnull', True), ('ended_at__gte', models.F('started_at')), _connector='OR'), name='attendance_session_end_after_start'),
        ),
    ]
