# Generated by Django 6.1.1 on 2026-09-14 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_pairing_sessions'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='approved_overtime_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='calculated_overtime_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='check_out_by_rule',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='early_out_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='is_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='review_reason',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='review_status',
            field=models.CharField(choices=[('clean', 'Clean'), ('needs_review', 'Needs review'), ('reviewed', 'Reviewed')], default='clean', max_length=16),
        ),
    ]
