# Generated by Django 6.1.1 on 2026-09-14 11:44

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_day_close_review'),
        ('devices', '0003_device_server_address'),
        ('employees', '0002_assignment_company_department'),
        ('tenants', '0005_alter_feature_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work_date', models.DateField()),
                ('correction_type', models.CharField(choices=[('add_scan', 'Added a scan'), ('change_status', 'Changed the status'), ('accept_review', 'Accepted as it is')], max_length=16)),
                ('proposed_event_at', models.DateTimeField(blank=True, null=True)),
                ('proposed_status', models.CharField(blank=True, max_length=16)),
                ('accepted_review_reason', models.CharField(blank=True, max_length=120)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('applied', 'In force'), ('superseded', 'Replaced by a later change'), ('withdrawn', 'Withdrawn')], default='applied', max_length=16)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True)),
                ('before_snapshot', models.JSONField(blank=True, default=dict)),
                ('after_snapshot', models.JSONField(blank=True, default=dict)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_corrections', to='employees.employee')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('withdrawn_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payroll_attendance_correction',
                'ordering': ('-created_at',),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='punchallocation',
            name='attendance_correction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='attendance.attendancecorrection'),
        ),
        migrations.AddConstraint(
            model_name='punchallocation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('attendance_correction__isnull', True), ('punch_event__isnull', False)), models.Q(('attendance_correction__isnull', False), ('punch_event__isnull', True)), _connector='OR'), name='punch_allocation_exactly_one_source'),
        ),
        migrations.AddIndex(
            model_name='attendancecorrection',
            index=models.Index(fields=['company', 'employee', 'work_date'], name='payroll_att_company_4c6ea1_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendancecorrection',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('correction_type', 'add_scan'), _negated=True), ('proposed_event_at__isnull', False), _connector='OR'), name='attendance_correction_scan_has_time'),
        ),
        migrations.AddConstraint(
            model_name='attendancecorrection',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('correction_type', 'change_status'), _negated=True), ('proposed_status__in', ['present', 'half_day', 'absent']), _connector='OR'), name='attendance_correction_status_is_settable'),
        ),
        migrations.AddConstraint(
            model_name='attendancecorrection',
            constraint=models.UniqueConstraint(condition=models.Q(('correction_type', 'change_status'), ('status', 'applied')), fields=('company', 'employee', 'work_date'), name='uniq_attendance_correction_status_in_force'),
        ),
    ]
