# Generated by Django 6.1.1 on 2026-09-26 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_missed_scan_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='missedscanrequest',
            name='correction_out',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='missed_scan_requests_out', to='attendance.attendancecorrection'),
        ),
        migrations.AddField(
            model_name='missedscanrequest',
            name='kind',
            field=models.CharField(choices=[('scan', 'A missed scan'), ('check_in', 'Missing check-in'), ('check_out', 'Missing check-out'), ('both', 'Missing check-in and check-out'), ('whole_day', 'A whole missing day')], default='scan', max_length=16),
        ),
        migrations.AddField(
            model_name='missedscanrequest',
            name='scan_out_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
