# Generated by Django 6.1.1 on 2026-09-27 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_missed_scan_kinds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancecorrection',
            name='correction_type',
            field=models.CharField(choices=[('add_scan', 'Added a scan'), ('change_status', 'Changed the status'), ('accept_review', 'Accepted as it is'), ('excuse_late', 'Late approved')], max_length=16),
        ),
    ]
