# Generated by Django 6.1.1 on 2026-09-29 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_profile_actions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='attendance_status',
            field=models.CharField(choices=[('present', 'Present'), ('half_day', 'Half day'), ('absent', 'Absent'), ('leave', 'Leave'), ('holiday', 'Holiday'), ('weekly_off', 'Weekly off'), ('incomplete', 'Incomplete'), ('inactive', 'Inactive')], max_length=16),
        ),
    ]
