# Generated by Django 6.1.1 on 2026-10-03 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_inactive_periods'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='in_office_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
