# Generated by Django 6.1.1 on 2026-10-06 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_in_office_minutes'),
        ('tenants', '0007_developer_api_feature'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceDayBuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField()),
                ('built_at', models.DateTimeField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.company')),
            ],
            options={
                'db_table': 'attendance_day_build',
                'constraints': [models.UniqueConstraint(fields=('company', 'work_date'), name='uniq_attendance_day_build')],
            },
        ),
    ]
