# Generated by Django 6.1.1 on 2026-10-06 06:00

import django.db.models.deletion
from django.db import migrations, models


def forget_builds(apps, schema_editor):
    """Days built before change times existed have none: build them again, once,
    so each open day gets its own."""
    apps.get_model("attendance", "AttendanceDayBuild").objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_day_build'),
        ('employees', '0007_inactive_periods'),
        ('tenants', '0007_developer_api_feature'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceDue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField()),
                ('due_at', models.DateTimeField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='employees.employee')),
            ],
            options={
                'db_table': 'attendance_due',
                'indexes': [models.Index(fields=['company', 'due_at'], name='attendance__company_3ce172_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'employee', 'work_date'), name='uniq_attendance_due')],
            },
        ),
        migrations.RunPython(forget_builds, migrations.RunPython.noop),
    ]
